# DATABASE

server:
  port: 8234

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/qsl?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    username: sbsst
    password: sbs123414
# JPA
  jpa:
    hibernate:
      ddl-auto: update
# CONSOLE
  output:
    ansi:
      enabled: always
